#######################################################################################
#######################################################################################
#######################################################################################
#####                                                                             #####
#####                          SaberCoreX 1.0                                     #####
#####                        Created By Driftay                                   #####
#####                                                                             #####
#######################################################################################
#######################################################################################
#######################################################################################
#<-------------------------------------->NOTES<-------------------------------------->#
#All Color Codes Can Be Used!
#Refer to: https://wiki.ess3.net/mc/
#Enable and Disable Any Module by Simply Switching Variable to true or false!
#<-------------------------------------->NOTES<-------------------------------------->#
modules:
  #Disable Piston AutoFarms
  anti_auto_farm: true

  #Disables The Spawning Of Baby Zombies
  anti_baby_zombie: true

  #Disables Placement of Boats and Minecarts
  anti_boat_minecart: true

  #Disable Cobble Monsters
  anti_cobble_monster: true

  #Disables Glitching Of Creepers
  anti_creeper_glitch: true

  #Disables ALL FORMS Of Teleportation For Dragon Eggs
  anti_dragonegg_teleport: true

  #Disables All Explosion Damage To Players
  anti_explosion_damage: true

  #Deny Items From Being Exploded/Burned
  anti_item_destory: true

  #Deny Certain Items From Being Stored Anywhere
  anti_item_storage: false

  #Disable All Forms Of Join Quit Messages
  anti_joinquit_messages: true

  #Disables AI/Targeting of Mobs
  anti_mob_ai: true

  #Disables Movement of Certain Entities
  anti_mob_movement: true

  #Disables Players Mining Spawners In a Configurable Radius Whilst Players Are Near
  anti_spawner_mine: true

  #Disable Blazes From Taking Water Damage
  anti_water_blaze: true

  #Disable Spawners From Spawning In Wilderness
  anti_wilderness_spawner: true

  #Command That Allows a Virtual Anvil.
  anvil_inventory: true

  #Automatically Switch Armor From Hotbar By Simply Right Clicking
  armor_swap: true

  #Automatically Respawn
  auto_respawn: true

  #Overall Border Patches For World Border
  border_patches: true

  #Enables a dynamic word filtering system via /chatfilter.
  chat_filter: true

  #Enabled a enhanced Chunk-busting system
  chunkbusters: true

  #Denies Users To Specific Commands
  disabled_commands: true

  #Instantly Breaks Sponges When Swung At
  insta_sponge_break: true

  #Limit Players Fly Height on the Y-Axis
  max_fly_height: true

  #Soak Water/Lava Up With Sponges In a Configurable Radius
  soak_sponges: true

  #Soak Water/Lava Up With Spawners In a Configurable Radius
  spawner_sponge: true


settings:
  sponge-radius: 3

  chunkbuster:
    async-mode: false #Will Destroy Layer By Layer if Enabled.
    warmup: 10 #In Seconds, timer will run before busting chunk.
    hologram:
      format: '&c&l[!] &7ChunkBuster' #Hologram Format for Chunkbuster When Placed
      enabled: true #Requires Holographic Displays
    item:
      displayname: '&c&lChunkBuster'
      lore:
        - '&f'
        - '&7&o(( Tip: Placing this &c&ochunkbuster&7&o will &a&oautomatically'
        - '&7&oremove the chunk upon &a&oplacement&7&o! ))'
        - '&f'
        - '&4&l* &cObtained from: &fstore.mystore.com'

  anti-spawner-mine-radius: 80

  armor-swap:
    cooldown: 500 #This is in Milliseconds - 500 = .5 seconds
    play-sound: true
    sound: 'LEVEL_UP'

  max-fly-height:
    limit: 255.5
    damage-player: true #Will Damage The Player For 1/2 a Heart

  denied-storage:
    - 'SPAWNER'

  chat-filter:
    format: '&b&l[Filtered] &e{player}&f: {message}'
    chat-slow-time: 0
    filtered-words:
      - nigger
      - faggot
      - queer
      - slut
      - whore
    whitelisted-links:
      - youtube.com
      - gyazo.com
      - discord.gg
      - twitter.com
      - saber.dev
    filtered-phrases:
      - saber is awesome

  anti-mob-movement:
    - 'CREEPER'
    - 'ZOMBIE'
    - 'GHAST'
    - 'SPIDER'
    - 'BLAZE'

  disabled-commands:
    - /icanhasbukkit
    - /ver
    - /version
    - /pl
    - /?
    - /plugins

  lightning-deny:
    - "DIAMOND_HELMET"
    - "DIAMOND_CHESTPLATE"
    - "DIAMOND_LEGGINGS"
    - "DIAMOND_BOOTS"
    - "DIAMOND_SWORD"
    - "DIAMOND_AXE"
    - "DIAMOND_PICKAXE"
    - "MOB_SPAWNER"
    - "HOPPER"

  explosion-deny:
    - "DIAMOND_HELMET"
    - "DIAMOND_CHESTPLATE"
    - "DIAMOND_LEGGINGS"
    - "DIAMOND_BOOTS"
    - "DIAMOND_SWORD"
    - "DIAMOND_AXE"
    - "DIAMOND_PICKAXE"
    - "MOB_SPAWNER"
    - "HOPPER"

  burn-deny:
    - "DIAMOND_HELMET"
    - "DIAMOND_CHESTPLATE"
    - "DIAMOND_LEGGINGS"
    - "DIAMOND_BOOTS"
    - "DIAMOND_SWORD"
    - "DIAMOND_AXE"
    - "DIAMOND_PICKAXE"
    - "MOB_SPAWNER"
    - "HOPPER"