name: SaberCoreX
main: me.driftay.core.SaberCore
author: Driftay
version: ${project.version}

commands:
  saberload:
    description: Reload SaberCoreX Configuration
    usage: /<command>
    aliases: [saberreload, sreload]
  saberunregister:
    description: Unregister a specific module.
    usage: /<command>
    aliases: [saberunload, sunload]
  saberregister:
    description: Register a specific module.
    usage: /<command>
    aliases: [saberload, sload]

permissions:
  sabercore.harvester.give:
    description: Ability to give users harvester hoes
  sabercore.ping.other:
    description: Ability to see other players ping
  sabercore.jellylegs:
    description: Ability to toggle on and off jelly legs
  sabercore.nightvision:
    description: Ability to toggle on and off nightvision
  sabercore.shockwave.give:
    description: Ability to grant players shockwaves
  sabercore.chunkbusters.give:
    description: Ability to grant players chunkbusters
  sabercore.disabledcommands.bypass:
    description: Bypass Disabled Commands
  sabercore.spawnermine.bypass:
    description: Bypass Spawner Mine Whilst Enemies Are Nearby
  sabercore.staff:
    description: Bypass Chat Mute
  sabercore.chatdelay.bypass:
    description: Bypass Chat Delay
  sabercore.chatfilter.bypass:
    description: Bypass Chat Filter
  sabercore.anvil:
    description: Use Virtual Anvil