name: SaberCoreX
main: me.driftay.core.SaberCore
author: Driftay
version: ${project.version}

permissions:
  sabercore.disabledcommands.bypass:
    description: Bypass Disabled Commands
  sabercore.spawnermine.bypass:
    description: Bypass Spawner Mine Whilst Enemies Are Nearby
  sabercore.staff:
    description: Bypass Chat Mute
  sabercore.chatdelay.bypass:
    description: Bypass Chat Delay
  sabercore.chatfilter.bypass:
    description: Bypass Chat Filter