name: SaberCoreX
main: me.driftay.core.SaberCore
author: Driftay
version: ${project.version}

commands:
  saberload:
    description: Reload Recluse Configuration
    usage: /<command>
    aliases: [saberreload, sreload]
  saberunregister:
    description: Unregister a specific patch.
    usage: /<command>
    aliases: [saberunload, sunload]
  saberregister:
    description: Register a specific patch.
    usage: /<command>
    aliases: [saberload, sload]

permissions:
  sabercore.disabledcommands.bypass:
    description: Bypass Disabled Commands
  sabercore.spawnermine.bypass:
    description: Bypass Spawner Mine Whilst Enemies Are Nearby
  sabercore.staff:
    description: Bypass Chat Mute
  sabercore.chatdelay.bypass:
    description: Bypass Chat Delay
  sabercore.chatfilter.bypass:
    description: Bypass Chat Filter
  sabercore.anvil:
    description: Use Virtual Anvil